### ISSUE TITLE
Bug devido à pergunta fora do laço. 

### ISSUE THREAD

**Issue by flavioduart** [hgees/infogas01#10]
De acordo com o código atual, caso o usuário diga sim na pergunta fora do laço o programa dirá automaticamente a velocidade média total e o consumo total. Não há espaço para inserir os dados e também não é mostrado as informações comuns a cada parada.

**Comment by guidoferrario** [comment]
Acredito que seia interessante encontrarmos uma maneira de retirar a pergunta fora do laço.

**Comment by CassiaReginaFBarbosa** [comment]
Sendo assim, talvez seja preciso inserir novamente os "cálculos" de cada parada após o laço, para a última parada.

**Comment by wagner-lucas** [comment]
Gente eu estava analisando e percebi outro detalhe, que deixando o código desse jeito é obrigatório ele dar no mínimo uma parada, ne melhor deixar tudo dentro do laço tbm não?.

**Comment by iWarhead** [comment]
Concordo com o Wagner.

**Comment by iWarhead** [comment]
Concordo com o Wagner, melhor deixar tudo dentro do laço.

**Comment by RafaelRSPX** [comment]
Para testar, podemos deixar a primeira parte do programa na forma de comentário e compilar para ver se dar certo.
