### ISSUE TITLE
Issues?

### ISSUE THREAD

**Issue by drbeco** [hgees/infogas01#3]
Coloquem aqui as discussões sobre planos e bugs.
Marquem milestones.
Marquem tags.
Abram, discutam, fechem, usem e abusem.

**Comment by RafaelRSPX** [comment]
Possível bug encontrado no arquivo infogas.gpt. Acredito que na ultima edição do arquivo infogas.gpt há um bug na variação entre o odômetro atual e o odômetro inicial. Compilei o programa nessa edição e o resultado da velocidade média do trecho ficou incoerente.

**Comment by pontesupe** [comment]
Possivelmente uma das variáveis do odômetro está incorreta na função.

**Comment by RafaelRSPX** [comment]
[BUG] Outro bug que verifiquei é um possível erro no resultado da velocidade média parcial, o a variação dos minutos pode dar um valor negativo e influenciar no resultado final da velocidade média.

**Comment by CassiaReginaFBarbosa** [comment]
Esse problema do minuto negativo pode ser resolvido usando uma condicional no código.

**Comment by flavioduart** [comment]
Talvez fosse melhor procurar uma forma de deixar o resultado do minuto em módulo, pra evitar esse bug.

**Comment by wagner-lucas** [comment]
acho que em modulo seria o certo, pois pode evitar até possiveis bugs no laço.

**Comment by guidoferrario** [comment]
Acho que não será necessária a utilização do módulo.

**Comment by hgees** [comment]
Concordo com Guido, talvez outra solução deva ser tomada, algo como somar 60 ao valor negativo do minuto

**Comment by alessonrenato** [comment]
tentaremos essa solução
