### ISSUE TITLE
Fork?

### ISSUE THREAD

**Issue by drbeco** [hgees/infogas01#4]
Não fazer fork.

Todos vão trabalhar no repositório ORIGINAL (hgees/infogas01)

Fork só irá confundir e não será considerado!

Corrijam, apaguem os forks. (edited, typo)

**Comment by hgees** [comment]
Só para não passar o engano, o repositório original é hgees/infogas01 e não tonyfrance/infogas03. Apenas avisando para não causar confusão aos desavisados

att. Héricles Gabriel Escoteiro e Silva

**Comment by hgees** [comment]
E professor Ruben, Boa noite, 
Vamos correr atrás e resolver este problema em breve

**Comment by drbeco** [comment]
Obrigado, Héricles. Editado.

**Comment by pontesupe** [comment]
Pronto, repositório deletado.
