### ISSUE TITLE
Melhorar documentacao

### ISSUE THREAD

**Issue by AldairSoares** [hgees/infogas01#7]
Pessoal,

Eu comentei cada variavel e gostaria de pedir que voces melhorassem, se possivel.

**Comment by flavioduart** [comment]
Acredito que realmente fique melhor padronizar as variáveis, porém é mais conviniente alterar apenas após o programa estar funcional.

**Comment by RafaelRSPX** [comment]
De fato, também acredito que fique melhor padronizar as variáveis do infogas.c com as variaveis infogas.gpt

**Comment by AldairSoares** [comment]
Eu organizei um pouco no intuito de facilitar o trabalho. Tendo cada variável com sua respectiva função bem explicada, qualquer outra alteração no código, ou a possível padronização das mesmas(no objetivo de relacionar os dois arquivos), dará uma praticidade maior ao nosso trabalho em conjunto.

**Comment by alessonrenato** [comment]
Boa ideia, variáveis padronizadas como foi discutido na presença do grupo :)

**Comment by AldairSoares** [comment]
Alesson,

Gostaria de saber se no momento em que você padronizou as variáveis, você também apagou os comentários ao lado delas.

**Comment by AldairSoares** [comment]
Alesson,

Gostaria de saber se durante a padronização das variáveis, você apagou os comentários ao lado de cada uma. Porque agora eu não consigo saber o que cada variável é.

**Comment by CassiaReginaFBarbosa** [comment]
Realmente os comentários foram apagados, mas serão adicionados novamente e atualizados.

**Comment by alessonrenato** [comment]
Sim, desculpe apagamos quando inserimos a padronização, será corrigido.

**Comment by hgees** [comment]
Problema corrigido
