### ISSUE TITLE
Tempo em hora quebrada.

### ISSUE THREAD

**Issue by RafaelRSPX** [hgees/infogas01#8]
Consegui deixar a previsão de chegada em horas quebradas. Há algum jeito de deixar em minutos? Na forma HH:MM?

**Comment by CassiaReginaFBarbosa** [comment]
Já temos os minutos e horas em variáveis diferentes, mas quando calculamos a velocidade média, estas se tornam apenas uma. Precisamos encontrar uma forma de transformar esses "restos de hora" de volta para minutos, para que a previsão seja dada corretamente.

**Comment by alessonrenato** [comment]
acho que consegui resolver

/*algoritmo de conversao da previsao de chegada*/

        enquanto horacheg < prevcheg - 1 faça
            horacheg := horacheg + 1;
        fim-enquanto

        prevcheg := prevcheg - horacheg;

        mincheg := prevcheg * 60;
        mincheg := mincheg + minat;

        se mincheg > 59 então
            mincheg := mincheg - 60;
            horacheg := horacheg + 1;
        fim-se
        horacheg := horacheg + horat;
        se horacheg > 23 então
            horacheg := horacheg - 24;
        fim-se

/*fim alg prev cheg*/

**Comment by RafaelRSPX** [comment]
Ok. Problema resolvido. Obrigado Alesson.
