### ISSUE TITLE
Repetição no infogas.gpt

### ISSUE THREAD

**Issue by CassiaReginaFBarbosa** [hgees/infogas01#9]
No arquivo em g-portugol, a parte da primeira parada que se encontra fora do laço e a parte das outras que se encontra dentro do laço são praticamente idênticas. Deveríamos procurar uma forma de reduzir o código, mantendo a funcionalidade. Temos que considerar também a possibilidade do usuário fazer apenas uma única parada.

**Comment by alessonrenato** [comment]
pois é, alvez dê pra só usar o código dentro do laço.

**Comment by hgees** [comment]
Estamos trabalhando nisso Cassia mas por enquanto ele só está rodando assim

**Comment by RafaelRSPX** [comment]
Exato, a versão atual do programa sugere que o motorista faça uma parada para abastecer pelo menos. Além disso, arquivo possue grande quantidade de linhas. Precisamos corrigir este problema. Possivelmente a solução oferecida por Alesson resolva o problema.

**Comment by flavioduart** [comment]
Fazendo todas partes dentro do laço como Alesson falou, diminuirá o código e possivelmente manterá a funcionalidade.

**Comment by pontesupe** [comment]
Se realmente for possível, recomendo que modifiquem na versão futura do programa v0.4

**Comment by guidoferrario** [comment]
Realmente, há o problema. Acho que podemos corrigi-lo da maneira que Alesson citou.
